/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package rpc.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AddService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AddService\",\"namespace\":\"rpc.service\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"avro.domain\",\"fields\":[{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}],\"messages\":{\"add\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"},\"sendUser\":{\"request\":[{\"name\":\"u\",\"type\":\"avro.domain.User\"}],\"response\":\"null\"}}}");
  int add(int a, int b) throws org.apache.avro.AvroRemoteException;
  java.lang.Void sendUser(avro.domain.User u) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AddService {
    public static final org.apache.avro.Protocol PROTOCOL = rpc.service.AddService.PROTOCOL;
    void add(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void sendUser(avro.domain.User u, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}